language: php
sudo: false
php:
    - 7.1.3
    - 7.2

addons:
    code_climate:
        repo_token:
            secret: "QBDaBShf8JMlQNOsnm9UAwTEnzZcLCF3zO6FX3KLIgCI+OfLQzy4qjW3bJc40Bm4dhvVCE7lBKz3+GI5JSLq2ZD0xbvzL0ITRVUt3R9JJRx/scFVK4LO+KFYKwOMaCz7z6kkOTjjuGpbdASiYBd05bRv1CAdH1NtY920a3sKa2nidTeRlYpdEMcFyRTptW9hrlW8w7InSmZS5950BXQs8KME4JJUDIUHbEJiwedtgDONrPTgJyxcn7/B2Svpq/6ymiUvBuZs+4nj84VmwaU0BUdGkAr9Dp8iCnAtuCoX6tfYBEqEgOiKTMxeJQca5MBS1LiQXpGI4+geDz/cu4TQ3YKtYe+k9RRawTmXwtnDL7vseOxuMi6/8tVBEnxhOkAqWtM/tP/ZvfSNrQMHS2BridrLx94HghJUwpX9dwgQd9crL/aPg8jPX9IofvECyrtjHvw1gLxr3Pi+2ECZ1qM14kPqZ3xfSi87VG17mZz3QgN+Ggyz2pKavdSkOOPtaODXU8XrPTfPTAU//6FcIe++95HXCYuYjtsOBXXL5NOvHHws0BAoYXywKmNrKHQNYQD2zX/SkbAdTolFsg/by+DyV7/25aQgTpBGC0pxMpAUpzqaqNSDOr2NsGiGMAihEERrIfc6c+oSI+3HMcBSSRf7nm0ZxJA1js7VoDcesXP+gZg="

before_script:
    - cp .travis.env .env
    - composer self-update
    - composer update --no-scripts

script:
    - vendor/bin/phpunit

after_success:
    - vendor/bin/test-reporter

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
    fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always